name: CI Pipeline

# main 브랜치에 코드가 push되거나 PR이 날아오면 자동으로 실행
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 체크아웃 (소스코드 가져오기)
    - name: Checkout source code
      uses: actions/checkout@v4

    # 2. Docker Hub 로그인 (우리가 저장한 Secret 활용)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Docker 이미지 빌드 및 도커 허브로 푸시
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # ★★★ 아래 '본인_도커허브_ID'를 실제 본인의 Docker Hub ID로 바꿔주세요!
        tags: |
          jangst15@gmail.com/k8s-demo-app:latest
          jangst15@gmail.com/k8s-demo-app:${{ github.sha }}
